# Generated by Django 3.1.2 on 2020-11-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201104_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.IntegerField(default=0),
        ),
    ]
